// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ejercicio4Modulo3.Models;

public partial class Proveedor
{
    public int Id { get; set; }

    public string CodProveedor { get; set; }

    public string RazonSocial { get; set; }
}